<<<<<<< HEAD
version: '3.8'
services:
  postgres:
    container_name: spring_db
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
=======

services:
  postgres:
    container_name: split_and_share_db
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
>>>>>>> 081c5cfa0654dfca65ba31d43b2eb6a236b7aaeb
      - POSTGRES_DB=split_and_share
    ports:
      - "5122:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
<<<<<<< HEAD
    container_name: split_and_share    
=======
    container_name: project_split_and_share    
>>>>>>> 081c5cfa0654dfca65ba31d43b2eb6a236b7aaeb
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
    ports:
      - "8088:8080"