name: CI/CD Pipeline

on:
  push:
    branches: [ main-backup ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies (Maven)
        run: mvn clean install -DskipTests
  
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests (Maven)
        run: mvn test -Dtest=sg.edu.ntu.split_and_share.service.UserServiceImplTest,sg.edu.ntu.split_and_share.service.ExpenseServiceImplTest,sg.edu.ntu.split_and_share.controller.ExpenseControllerTest.java
  
  build-docker-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "<span class="math-inline">\{\{ secrets\.DOCKERHUB\_PASSWORD \}\}" \| docker login \-u "</span>{{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t bindugopinathan/project_split_and_share:tagname .
      - name: Push Docker Image to Docker Hub
        run: docker push bindugopinathan/project_split_and_share:tagname
  
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: build-docker-image
    steps:
      - uses: actions/checkout@v3
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sudo bash
      - name: Login to Heroku
        run: heroku container:login
      - name: Set Heroku Stack
        run: heroku stack:set container -a bindu-split-and-share
      - name: Push Container Image to Heroku
        run: heroku container:push web -a bindu-split-and-share
      - name: Release Container Image on Heroku
        run: heroku container:release web -a bindu-

