name: Docker Image CI

on:
  push:
    branches: [ $default-branch ]
  pull-request:
    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      runs: docker build .